[package]
name = "day_21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
num = "0.4.1"
itertools = "0.12.0"
memoize = "0.4.1"
